// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08/04/2025, 21:40:43
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/everton/everton-tenorio/everton-tenorio.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/plugins/**/*.{js,ts,mjs}","/home/everton/everton-tenorio/everton-tenorio.github.io/composables/**/*.{js,ts,mjs}","/home/everton/everton-tenorio/everton-tenorio.github.io/utils/**/*.{js,ts,mjs}","/home/everton/everton-tenorio/everton-tenorio.github.io/pages/index.vue","/home/everton/everton-tenorio/everton-tenorio.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/everton/everton-tenorio/everton-tenorio.github.io/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;